repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
    - id: check-yaml
      stages: [commit]
    - id: check-json
      stages: [commit]
    - id: trailing-whitespace
      stages: [commit]
      exclude: ".*/migrations/.*"
    - id: end-of-file-fixer
      stages: [commit]
      exclude: ".*/migrations/.*|.*/pkcs11.txt"
